version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: original_db
      POSTGRES_USER: akhilgovmb
      POSTGRES_PASSWORD: testpostgres
    ports:
      - "5433:5432"
    volumes:
      - "C:/Users/akhilgovmb/docker/pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akhilgovmb -d original_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "test1234"]
    ports:
      - "6379:6379"
    volumes:
      - "C:/Users/akhilgovmb/docker/redisdata:/data"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  auth:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    environment:
      - CONFIG_PATH=/config/config.yaml
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "50051:50051"
    volumes:
      - "C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro"

  app:
    build:
      context: .
      dockerfile: ./cmd/subscription-aggregator/Dockerfile
    restart: always
    environment:
      - CONFIG_PATH=/config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - "C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro"

  scheduler:
    build:
      context: .
      dockerfile: ./cmd/scheduler/Dockerfile
    environment:
      - CONFIG_PATH=/config/config.yaml
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - "C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro"

  sender:
    build:
      context: .
      dockerfile: ./cmd/sender/Dockerfile
    environment:
      - CONFIG_PATH=/config/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
      # notification-scheduler:
    volumes:
      - "C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro"

  payment-processor:
    build:
      context: .
      dockerfile: ./cmd/payment-processor/Dockerfile
    environment:
      - CONFIG_PATH=/config/config.yaml
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - "C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro"

volumes:
  pgdata:
  redisdata: