services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: original_db
      POSTGRES_USER: papa
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - /home/papa/docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U papa -d original_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "test1234"]
    ports:
      - "6379:6379"
    volumes:
      - /home/papa/docker/redisdata:/data
    restart: always

  auth-service:
    build:
      context: .
      dockerfile: ./cmd/auth-service/Dockerfile
    environment:
      - CONFIG_PATH=/config/config.yaml
      - JWT_SECRET_KEY=aQwerty12345!@#SecretKeyExample67890_+
      - TOKEN_TTL=24h
      - STORAGE_CONNECTION_STRING=postgres://papa:1234@db:5432/original_db?sslmode=disable
      - REDIS_ADDRESS=redis:6379
      - REDIS_PASSWORD=test1234
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "50051:50051"
    volumes:
      - /home/papa/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro

  app:
    build:
      context: .
      dockerfile: ./cmd/subscription-aggregator/Dockerfile
    restart: always
    environment:
      - CONFIG_PATH=/config/config.yaml
      - JWT_SECRET_KEY=aQwerty12345!@#SecretKeyExample67890_+
      - TOKEN_TTL=24h
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=original_db
      - DB_USER=papa
      - DB_PASSWORD=1234
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=test1234
      - GRPC_AUTH_ADDRESS=auth-service:50051
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      auth-service:
        condition: service_started
    volumes:
      - /home/papa/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro

volumes:
  pgdata:
  redisdata:
