services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: papa
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - "/docker/pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U papa -d test"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    environment:
      - CONFIG_PATH=/config/config.yaml
      - JWT_SECRET=aQwerty12345!@#SecretKeyExample67890_+
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=papa
      - DB_PASSWORD=1234
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /home/papa/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro


volumes:
  pgdata:
