services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: original_db
      POSTGRES_USER: papa
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - /home/papa/docker/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U papa -d original_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "test1234"]
    ports:
      - "6379:6379"
    volumes:
      - /home/papa/docker/redisdata:/data
    restart: always

  app:
    build: .
    restart: always
    environment:
      - CONFIG_PATH=/config/config.yaml
      - JWT_SECRET=aQwerty12345!@#SecretKeyExample67890_+ - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=original_db
      - DB_USER=papa
      - DB_PASSWORD=1234
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=test1234
      - TEST_POSTGRES=postgres://papa:1234@localhost:5433/test?sslmode=disable  ## бд для тестов
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - /home/papa/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro
  test:
    build: .
    environment:
      - TEST_POSTGRES=postgres://papa:1234@db:5432/test?sslmode=disable
    depends_on:
      - db
      - redis
    command: ["go", "test", "./...", "-v"]



volumes:
  pgdata:
  redisdata:
