services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: akhilgovmb
      POSTGRES_PASSWORD: testpostgres
    ports:
      - "5433:5432"
    volumes:
      - "C:/docker/pgdata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akhilgovmb -d test"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      - CONFIG_PATH=/config/config.yaml
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=test
      - DB_USER=akhilgovmb
      - DB_PASSWORD=testpostgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - C:/Users/akhilgovmb/Desktop/Subscription-aggregator/config/config.yaml:/config/config.yaml:ro


volumes:
  pgdata:
