version: "3"

tasks:
  generate_auth:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I internal/grpc/proto internal/grpc/proto/auth.proto --go_out=internal/grpc/gen --go_opt=paths=source_relative --go-grpc_out=internal/grpc/gen/ --go-grpc_opt=paths=source_relative