env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8080"
  timeout: 4s ## время на чтение запроса, время на отправку ответа
  idle_timeout: 60s ## время жизни соединения с клиентом