basePath: /api/v1
definitions:
  github_com_magabrotheeeer_subscription-aggregator_internal_http-server_response.Response:
    properties:
      data: {}
      error:
        type: string
      status:
        type: string
    type: object
  github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyCounterSumSubscriptionEntrys:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyCreaterSubscriptionEntry:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyFilterUpdaterSubscriptionEntry:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  github_com_magabrotheeeer_subscription-aggregator_internal_subscription.FilterReaderSubscriptionEntry:
    properties:
      end_date:
        type: string
      price:
        type: integer
      service_name:
        type: string
      start_date:
        type: string
      user_id:
        type: string
    type: object
  github_com_magabrotheeeer_subscription-aggregator_internal_subscription.FilterRemoverSubscriptionEntry:
    properties:
      service_name:
        type: string
      user_id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Сервис учёта подписок
  title: Subscription API
  version: "1.0"
paths:
  /subscriptions:
    delete:
      consumes:
      - application/json
      description: Удаляет подписки пользователя по service_name или все подписки
        пользователя если service_name не указан
      parameters:
      - description: Фильтры для удаления подписок
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_subscription.FilterRemoverSubscriptionEntry'
      produces:
      - application/json
      responses:
        "200":
          description: 'deleted_count: число удаленных записей'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка валидации данных
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Удалить подписки
      tags:
      - subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает полный список всех подписок с количеством записей
      produces:
      - application/json
      responses:
        "200":
          description: 'list_count: число, entries: массив подписок'
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Получить список всех подписок
      tags:
      - subscriptions
    post:
      consumes:
      - application/json
      parameters:
      - description: Новая подписка
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyCreaterSubscriptionEntry'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_http-server_response.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_http-server_response.Response'
      summary: Создать подписку
      tags:
      - subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет цену или даты подписки пользователя по service_name.
        Если указана цена - обновляется цена, иначе обновляются даты
      parameters:
      - description: Данные для обновления подписки
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyFilterUpdaterSubscriptionEntry'
      produces:
      - application/json
      responses:
        "200":
          description: 'updated_count: число обновленных записей'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка валидации данных или конвертации дат
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Обновить подписку
      tags:
      - subscriptions
  /subscriptions/filter:
    post:
      consumes:
      - application/json
      description: Возвращает список подписок пользователя согласно заданным фильтрам
      parameters:
      - description: Фильтры для поиска подписок
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_subscription.FilterReaderSubscriptionEntry'
      produces:
      - application/json
      responses:
        "200":
          description: 'read_count: число, entries: массив подписок'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка валидации данных
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Получить подписки по фильтру
      tags:
      - subscriptions
  /subscriptions/sum:
    post:
      consumes:
      - application/json
      description: Возвращает общую сумму подписок для конкретного пользователя и
        сервиса за указанный период
      parameters:
      - description: Параметры для подсчета суммы
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_magabrotheeeer_subscription-aggregator_internal_subscription.DummyCounterSumSubscriptionEntrys'
      produces:
      - application/json
      responses:
        "200":
          description: 'sum_of_subscriptions: число'
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Ошибка валидации или парсинга
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Внутренняя ошибка сервера
          schema:
            additionalProperties: true
            type: object
      summary: Получить сумму подписок за период
      tags:
      - subscriptions
swagger: "2.0"
