basePath: /api/v1
definitions:
  login.Request:
    properties:
      password:
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  models.DummyEntry:
    properties:
      counter_months:
        description: Количество месяцев
        type: integer
      price:
        description: Цена (>0)
        type: integer
      service_name:
        description: Название сервиса
        type: string
      start_date:
        description: Дата начала в формате 01-2006
        type: string
    required:
    - counter_months
    - price
    - service_name
    - start_date
    type: object
  models.DummyFilterSum:
    properties:
      counter_months:
        description: Количество месяцев подписки
        type: integer
      service_name:
        description: Название сервиса (опционально)
        type: string
      start_date:
        description: Дата начала периода
        type: string
    required:
    - counter_months
    - start_date
    type: object
  register.Request:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  response.ErrorResponse:
    properties:
      error:
        example: invalid request body
        type: string
      status:
        example: Error
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
  description: REST API сервис для работы с подписками (создание, удаление, обновление,
    получение, суммарный расчёт).
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Subscription Aggregator API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Аутентифицирует пользователя по имени и паролю. Возвращает JWT
        и refresh-токен.
      parameters:
      - description: Учетные данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/login.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная авторизация
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Неверные учетные данные
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Создает нового пользователя по email, username и password
      parameters:
      - description: Данные нового пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/register.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Успешная регистрация
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Ошибка валидации данных
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера при регистрации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Регистрация нового пользователя
      tags:
      - Auth
  /subscriptions:
    get:
      consumes:
      - application/json
      description: Возвращает список подписок пользователя с учетом пагинации (limit
        и offset).
      parameters:
      - description: Максимальное количество записей (по умолчанию 10)
        example: 10
        in: query
        minimum: 1
        name: limit
        type: integer
      - description: Смещение для пагинации (по умолчанию 0)
        example: 0
        in: query
        minimum: 0
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список подписок
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка при получении списка
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить список подписок пользователя
      tags:
      - Subscriptions
    post:
      consumes:
      - application/json
      description: Создает новую подписку для текущего пользователя. Возвращает ID
        созданной записи.
      parameters:
      - description: Данные новой подписки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DummyEntry'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание подписки
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера при создании подписки
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Создать новую подписку
      tags:
      - Subscriptions
  /subscriptions/{id}:
    delete:
      consumes:
      - application/json
      description: Удаляет подписку пользователя по её идентификатору. Возвращает
        количество удалённых записей.
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Подписка успешно удалена
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка при удалении
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Удалить подписку по ID
      tags:
      - Subscriptions
    get:
      consumes:
      - application/json
      description: Возвращает подписку по её уникальному идентификатору.
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Успешный ответ с данными
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный ID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Внутренняя ошибка сервера
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Получить подписку по ID
      tags:
      - Subscriptions
    put:
      consumes:
      - application/json
      description: Обновляет данные существующей подписки пользователя по идентификатору.
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      - description: Обновлённые данные подписки
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DummyEntry'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное обновление
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный ID или JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Подписка не найдена
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Ошибка валидации
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера при обновлении
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Обновить подписку по ID
      tags:
      - Subscriptions
  /subscriptions/sum:
    post:
      consumes:
      - application/json
      description: Подсчитывает общую сумму подписок пользователя с возможностью фильтрации.
      parameters:
      - description: Фильтры для подсчёта суммы
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.DummyFilterSum'
      produces:
      - application/json
      responses:
        "200":
          description: Успешный расчёт суммы
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Некорректный JSON
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "401":
          description: Пользователь не авторизован
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "422":
          description: Ошибка валидации фильтра
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Ошибка сервера при вычислении суммы
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Подсчёт суммы подписок
      tags:
      - Subscriptions
swagger: "2.0"
